services:
  - type: web
    name: snip
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BASE_URL
        sync: false          # you'll fill this in after first deploy
      - key: DATABASE_URL
        fromDatabase:
          name: urlsnip-db
          property: connectionString

databases:
  - name: urlsnip-db
    plan: free
    databaseName: urlshort
